[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npx prisma generate && npm start"
healthcheckPath = "/graphql"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
