[build]
builder = "NIXPACKS"
buildCommand = "yarn run build"

[deploy]
startCommand = "npx prisma migrate deploy && npm start"
healthcheckPath = "/graphql"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "18"

[env]
PORT = { default = "4000" }
